version: '3.4'

services:
  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: deandraper
      POSTGRES_PASSWORD: spacework1821
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  
  express-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3010:3000